import type { AgentSpecialistId } from "../../types";

export const AGENT_DEFINITIONS: Record<
  AgentSpecialistId,
  {
    identity: string;
    done: string;
    model: "orchestrator" | "worker";
    tools: string[];
    prefixes: string[];
  }
> = {
  orchestrator: {
    identity: "Route work, keep context, and finish with a concise answer.",
    done: "The user has a complete answer or a pending Accept/Connect action.",
    model: "orchestrator",
    tools: ["delegate_agent", "request_capability", "search_harness", "persist_memory", "submit_implementation_plan"],
    prefixes: ["fairlx_", "mail_", "github_", "security_", "agent_job", "coding_session"],
  },
  planner: {
    identity:
      "Write a shippable implementation plan. For build/change work, call submit_implementation_plan and wait for Accept. Do not fan out other specialists before that.",
    done: "A structured implementation plan with phases and tasks, waiting for Accept when required.",
    model: "worker",
    tools: [
      "search_harness",
      "submit_implementation_plan",
      "fairlx_work_item_list",
      "fairlx_sprint_list",
      "fairlx_project_get",
      "fairlx_project_list",
      "fairlx_project_create",
      "fairlx_project_members_list",
      "use_skill",
      "personal_read",
    ],
    prefixes: ["fairlx_work_item", "fairlx_sprint", "fairlx_doc", "fairlx_project"],
  },
  researcher: {
    identity: "Search Fairlx records, docs, repos, and the public web. Cite URLs from web_search and web_fetch. Do not write documents.",
    done: "Cited findings from tools, not guesses.",
    model: "worker",
    tools: [
      "search_harness",
      "web_search",
      "web_fetch",
      "file_search",
      "code_inspect",
      "github_read_file",
      "github_list_files",
      "github_list_repos",
      "fairlx_organization_get",
      "fairlx_organization_list",
      "fairlx_organization_workspaces_list",
      "fairlx_workspace_get",
      "mcp_resources",
      "personal_read",
    ],
    prefixes: ["fairlx_", "github_read", "github_list"],
  },
  builder: {
    identity:
      "Implement in the Azure coding-session sandbox with coding_session_implement (Claude Code or Codex) or coding_session_exec. Never github_write_file while a sandbox is bound. Never run git on the Fairlx host.",
    done: "Proposed or applied changes, waiting for Accept when required.",
    model: "worker",
    tools: [
      "use_skill",
      "create_project",
      "web_search",
      "web_fetch",
      "github_read_file",
      "github_list_files",
      "github_write_file",
      "github_open_pr",
      "github_merge_pr",
      "github_account_status",
      "github_list_repos",
      "github_list_owners",
      "github_create_repo",
      "github_link_repo",
      "github_update_repo",
      "github_delete_file",
      "github_list_prs",
      "github_list_issues",
      "github_create_issue",
      "coding_session_start",
      "coding_session_exec",
      "coding_session_status",
      "coding_session_implement",
      "coding_session_browser",
      "fairlx_work_item_create",
      "fairlx_work_item_update",
      "fairlx_work_item_bulk_update",
      "fairlx_sprint_create",
      "fairlx_sprint_plan",
      "fairlx_sprint_update",
      "fairlx_sprint_list",
      "fairlx_project_create",
    ],
    prefixes: ["github_", "fairlx_work_item", "fairlx_sprint", "fairlx_project", "fairlx_doc", "coding_session"],
  },
  git: {
    identity: "Inspect linked repos and open real GitHub PRs. Never run git on the Fairlx host.",
    done: "Repo status, file diffs, or a pull request URL.",
    model: "worker",
    tools: [
      "git_status",
      "git_stage",
      "git_unstage",
      "git_commit_plan",
      "github_read_file",
      "github_list_files",
      "github_write_file",
      "github_open_pr",
      "github_merge_pr",
      "github_create_repo",
      "github_link_repo",
      "github_update_repo",
      "github_list_repos",
      "coding_session_exec",
      "coding_session_implement",
    ],
    prefixes: ["git_", "github_", "coding_session"],
  },
  tester: {
    identity: "Run tests in the Azure coding-session sandbox. Never execute on the Fairlx host.",
    done: "Test command output from coding_session_exec.",
    model: "worker",
    tools: ["coding_session_exec", "coding_session_status", "coding_session_browser", "terminal", "github_read_file"],
    prefixes: ["coding_session", "terminal", "github_read"],
  },
  reviewer: {
    identity: "Review Fairlx in-app diffs and sandbox screenshots. Comment on the Fairlx diff, not only GitHub. Never grade your own work.",
    done: "Pass/fail with specific gaps.",
    model: "worker",
    tools: [
      "github_read_file",
      "github_list_files",
      "github_list_prs",
      "code_inspect",
      "search_harness",
      "fairlx_work_item_get",
      "fairlx_work_item_list",
      "coding_session_status",
      "coding_session_browser",
    ],
    prefixes: ["github_read", "github_list", "fairlx_work_item_get", "fairlx_work_item_list"],
  },
  ops: {
    identity: "Company actions: org/workspace invites, project teams, assignments, and mail when the user asked to send email.",
    done: "The person is invited or the requested company action is completed.",
    model: "worker",
    tools: [
      "mail_send",
      "notify_channel",
      "fairlx_work_item_get",
      "fairlx_work_item_list",
      "fairlx_work_item_update",
      "fairlx_work_item_bulk_update",
      "fairlx_comment_add",
      "fairlx_workspace_invite_get",
      "fairlx_workspace_member_add",
      "fairlx_workspace_members_list",
      "fairlx_organization_members_list",
      "fairlx_organization_get",
      "fairlx_organization_list",
      "fairlx_organization_workspaces_list",
      "fairlx_organization_update",
      "fairlx_project_team_create",
      "fairlx_project_member_add",
      "fairlx_project_team_member_add",
      "fairlx_project_team_list",
      "fairlx_usage_summary",
      "request_capability",
    ],
    prefixes: ["mail_", "fairlx_workspace", "fairlx_organization", "fairlx_project_member", "fairlx_project_team", "fairlx_comment", "fairlx_work_item", "fairlx_usage"],
  },
  security: {
    identity: "Review linked source for vulnerabilities. Cite file paths. Never exploit production.",
    done: "Verified findings with file paths, or a running security job id.",
    model: "worker",
    tools: [
      "security_review",
      "github_read_file",
      "github_list_files",
      "code_inspect",
      "agent_job_status",
      "request_capability",
    ],
    prefixes: ["security_", "github_read", "github_list", "agent_job"],
  },
  workflow: {
    identity: "Inspect and propose Fairlx workflow statuses and transitions.",
    done: "A concrete workflow change the user can Accept.",
    model: "worker",
    tools: ["fairlx_workflow_get", "search_harness", "use_skill"],
    prefixes: ["fairlx_workflow"],
  },
};

export function specialistToolAllowlist(id: AgentSpecialistId): { names: Set<string>; prefixes: string[] } {
  const def = AGENT_DEFINITIONS[id] ?? AGENT_DEFINITIONS.orchestrator;
  return { names: new Set(def.tools), prefixes: def.prefixes };
}
